# Generated by Django 3.0.5 on 2021-06-20 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210620_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titles',
            name='rating',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
