# Generated by Django 3.0.5 on 2021-06-26 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210622_2033'),
        ('api', '0002_auto_20210626_0238'),
    ]

    operations = [
    ]
