# Generated by Django 3.0.5 on 2021-06-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210622_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.TextField(verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='Информация о себе'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('moderator', 'Moderator'), ('user', 'User')], default='user', max_length=12, verbose_name='Уровень прав пользователя'),
        ),
        migrations.AlterField(
            model_name='genres',
            name='name',
            field=models.TextField(verbose_name='Название жанра'),
        ),
        migrations.AlterField(
            model_name='titles',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='titles',
            name='genre',
            field=models.ManyToManyField(blank=True, related_name='genres', to='api.Genres'),
        ),
        migrations.AlterField(
            model_name='titles',
            name='name',
            field=models.TextField(verbose_name='Название произведения'),
        ),
    ]
