# Generated by Django 3.0.5 on 2021-06-26 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_merge_20210626_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titles',
            name='genre',
            field=models.ManyToManyField(blank=True, null=True, related_name='genres', to='api.Genres'),
        ),
    ]
