# Generated by Django 3.0.5 on 2021-06-26 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210626_1524'),
        ('api', '0010_auto_20210626_1318'),
    ]

    operations = [
    ]
