# Generated by Django 3.0.5 on 2021-06-26 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_merge_20210626_2254'),
        ('api', '0009_remove_titles_rating'),
    ]

    operations = [
    ]
